name: CD
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Build & Deploy Website
        env:
          GIT_USER: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        run: |
          git config --global user.name "dti-github-bot"
          git config --global user.email "admin@cornelldti.org"
          yarn deploy
